"""empty message

Revision ID: a8fff2a564f3
Revises: 0c811852c243
Create Date: 2016-02-03 21:24:27.719743

"""

# revision identifiers, used by Alembic.
revision = 'a8fff2a564f3'
down_revision = '0c811852c243'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
